import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import "../styles/globals.css";

const courier_prime = Courier_Prime({
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={courier_prime.className}>{children}</body>
    </html>
  );
}
